### ISSUE TITLE
"Sorry, this member could be found"

### ISSUE THREAD

**Issue by iizxp** [MacPaw/together-app#1]
Upon trying to log in or pressing the "Sign In with SSO" button I'm getting

`"MemberNotFoundError: Sorry, this member _could be_ found.".`

Additional info:

- I'm deploying it without docker
- It's not necessary to try logging in in order to invoke the error
- I've followed this section, _but in order_ to fix the issue: https://github.com/MacPaw/together-app#using-a-custom-sso-or-oauth-provider
- The full output
```
npm run dev

> together-app@1.0.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/nr/apps/together-app/.env
info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 2.6s (342 modules)
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
wait  - compiling /_middleware...
event - compiled client and server successfully in 645 ms (396 modules)
wait  - compiling /login (client and server)...
event - compiled client and server successfully in 1584 ms (438 modules)
wait  - compiling /api/auth/[...nextauth]...
event - compiled client and server successfully in 536 ms (473 modules)
wait  - compiling /...
event - compiled client and server successfully in 499 ms (488 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 1111 ms (547 modules)
MemberNotFoundError: Sorry, this member could be found.
    at MemberProvider.getByEmail (webpack-internal:///./services/MemberProvider.ts:58:19)
    at async getServerSideProps (webpack-internal:///./pages/index.tsx:104:22)
    at async Object.renderToHTML (/home/nr/apps/together-app/node_modules/next/dist/server/render.js:589:20)
    at async doRender (/home/nr/apps/together-app/node_modules/next/dist/server/base-server.js:879:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/home/nr/apps/together-app/node_modules/next/dist/server/base-server.js:979:28)
    at async /home/nr/apps/together-app/node_modules/next/dist/server/response-cache.js:64:36 {
  status: 400,
  code: null,
  data: null
}
wait  - compiling /_error (client and server)...
```
- I've failed to run `npm run initialize`, the output message I get upon running is: 

```
> together-app@1.0.0 initialize
> node jobs-dist/initialize.js

Authorization is required!
Request failed with status code 401
```

I'd appreciate any hints on what I might've done wrong.

**Comment by raycharius** [comment]
@iizxp Hi, thanks for the issue, could you find me on Telegram using the same nickname I have here? Would like to help you in real time to get you up and running as quickly as possible

**Comment by raycharius** [comment]
Hi @iizxp, thanks for the issue! 

The first error is probably due to the fact that you've previously successfully logged in with the SSO or OAuth provider, so when you go to the main page, it skips the actual login and starts to process the request further, and since you were unable to run the `initialize` script, it's not finding the member in the database, as that script. 

After chatting with @iizxp, we realized the problem was: 

- The script was being called before the server was running.
- The `HOST` environment variable – the port wasn't included for `localhost`.

The jobs are simply HTTP requests to the server itself. I'll update the README to clarify that.

Thanks!
