### ISSUE TITLE
Chek-in location issue

### ISSUE THREAD

**Issue by andriikaplunenko** [MacPaw/together-app#3]
Hi !
Hope your team is fine and safe !
I am have some issues with setting the location during check-in process .
App can't obtain location automatically and when I am trying to set it manually it simply can't find any city 
In both cases log returns `together | LocationProviderError: Sorry, no place could be found. Please try again.`

`together | LocationProviderError: Sorry, no place could be found. Please try again.
together |     at LocationService.getApproximatedLocationByLatLong (webpack-internal:///(api)/./services/LocationService.ts:31:19)
together |     at runMicrotasks (<anonymous>)
together |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
together |     at async GetPlace (webpack-internal:///(api)/./pages/api/get-place.ts:17:26)
together |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:182:9)
together |     at async DevServer.runApi (/app/node_modules/next/dist/server/next-server.js:386:9)
together |     at async Object.fn (/app/node_modules/next/dist/server/base-server.js:488:37)
together |     at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32)
together |     at async DevServer.run (/app/node_modules/next/dist/server/base-server.js:600:29)
together |     at async DevServer.run (/app/node_modules/next/dist/server/dev/next-dev-server.js:445:20) {
together |   status: 400,
together |   code: 'couldNotFetchLocationData',
together |   data: null
together | }`

I am deploying the app locally with docker .

Any hints how to resolve this issue ? 
Thanks in advance

**Comment by raycharius** [comment]
Hi, thanks for the issue!

This could be an issue with the Google API tokens. I'll add some clarification to this to the README today, but let's first sync on the API token setup to make sure that's the issue.

There are two Google API token environment variables:

`GOOGLE_GEOCODING_API_TOKEN` – This token is used on the back end to fetch the human-readable place by geolocation coordinates, passed from the front end when geolocation is successfully used, and to do the same by `place_id` when the manual search is used on the front end.

`GOOGLE_PLACES_API_TOKEN` – This token is used on the front end for the autocomplete field when manually selecting a place. 

The tokens should be two different tokens, and here is some help with how to set those up:

`GOOGLE_GEOCODING_API_TOKEN` – This token simply needs to have the **Geocoding API** turned on in the **API restrictions** section.

`GOOGLE_PLACES_API_TOKEN` – This token needs to have two APIs included in the **API restrictions** section – the **Places API** and the **Maps JavaScript API**..

Additionally, you'll want to go to the **Application restrictions** section, and turn on **HTTP referrers (web sites)**. Then, below in the **Website restrictions** section, you'll want to include any domains you plan on deploying the application to. If you're developing locally, this particular restriction isn't important, but should definitely be enforced on production.

Please check to make sure your set up complies to this, and whether or not it works, thanks!

**Comment by andriikaplunenko** [comment]
Hi @raycharius

Thanks for your reply 
Indeed   my `GOOGLE_PLACES_API_TOKEN` got access only for `Places API` I have added access to `Maps JavaScript API` but issue still reproduces with exactly same error

**Comment by raycharius** [comment]
Could you get in touch via Telegram using the same handle I have here? We can try to debug this in real time

**Comment by raycharius** [comment]
After chatting, we realized there were two issues:

- The token in the `GOOGLE_GEOCODING_API_TOKEN` had been restricted by HTTP referrer, which does not work with calls from the back end.
- The account did not have billing activated and an added payment method.

I've updated the README to better reflect how to correctly get started with the Google API.

Thanks for the issue and collaboration!
