### ISSUE TITLE
[FEATURE] Ability to add grouping by division, team etc

### ISSUE THREAD

**Issue by niklissad** [MacPaw/together-app#7]
Hello. It would be great to have an ability to group company members by division, team etc

I didn't found any information about this feature in documentation

Is it possible?

**Comment by viktorshlapak** [comment]
Hello, how to track logs and diagnose the issue:
Updates for existing users are working fine, but new users added within the past 2 months are not being added. When attempting to do a Check-In for a different user who the program cannot find, it says that the user does not exist; however, I can select the user from the dropdown list in the form. Either npm reload and npm init or restart of docker is not helping....

**Comment by raycharius** [comment]
Hi @niklissad! 

Since there are so many different possible structures for a company and so many different HR systems to sync with, this is probably something we'd leave to each individual company to modify the logic and DB structure to reflect the company's needs.
